version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: deploy/dev/Dockerfile
      target: app
    environment:
      DB_NAME: hummus
      DB_USER: hummus
      DB_PASSWORD: password
      DB_HOST: postgres
      DEBUG: "true"
      HOST: localhost
      SECRET_KEY: secret
    volumes:
    - "media:/hummus/media"
  nginx:
    build:
      context: .
      dockerfile: deploy/dev/Dockerfile
      target: nginx
    ports:
    - "127.0.0.1:8000:80"
    volumes:
    - "media:/usr/share/nginx/html/media-redirect"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: hummus
      POSTGRES_USER: hummus
      POSTGRES_PASSWORD: password
volumes:
  media:
